FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app
COPY . ./
RUN dotnet restore Jotanunes.Worker/Jotanunes.Worker.csproj
RUN dotnet publish Jotanunes.Worker/Jotanunes.Worker.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .

ENV LANG=pt_BR.UTF-8

CMD ["dotnet", "Jotanunes.Worker.dll"]
