FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build-env
WORKDIR /app
COPY . ./
RUN dotnet restore Jotanunes.API.External/Jotanunes.API.External.csproj
RUN dotnet publish Jotanunes.API.External/Jotanunes.API.External.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build-env /app/out .

EXPOSE 80

ENV LANG=pt_BR.UTF-8
ENV ASPNETCORE_URLS=http://+:80

CMD ["dotnet", "Jotanunes.API.External.dll"]
