// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Jotanunes.External.BddTests.Features.Api.SupplierUserSessionTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SupplierUserSession_LoginFeature : object, Xunit.IClassFixture<SupplierUserSession_LoginFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features/Api/SupplierUserSessionTests", "SupplierUserSession - Login", "Como fornecedor com acesso ao Portal do Fornecedor\nQuero entrar com meu e-mail e " +
                "senha\nPara acessar as solicitações da minha empresa", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "LoginSupplierUserSession.feature"
#line hidden
        
        public SupplierUserSession_LoginFeature(SupplierUserSession_LoginFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
    await testRunner.GivenAsync("que existe uma empresa cadastrada com CNPJ \"11.222.333/0001-81\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Api/SupplierUserSessionTests/LoginSupplierUserSession.feature.ndjson", 8);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Entrar com credenciais válidas")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SupplierUserSession - Login")]
        [global::Xunit.TraitAttribute("Description", "Entrar com credenciais válidas")]
        public async global::System.Threading.Tasks.Task EntrarComCredenciaisValidas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Entrar com credenciais válidas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.GivenAsync("que existe um fornecedor \"maria@alfa.com.br\" com senha definitiva para a empresa " +
                        "cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 13
    await testRunner.WhenAsync("eu entrar com o e-mail \"maria@alfa.com.br\" e a senha correta", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 14
    await testRunner.ThenAsync("eu recebo uma resposta 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 15
    await testRunner.AndAsync("eu recebo um par de tokens vinculado à empresa cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Entrar com senha provisória indica que a senha deve ser trocada")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SupplierUserSession - Login")]
        [global::Xunit.TraitAttribute("Description", "Entrar com senha provisória indica que a senha deve ser trocada")]
        public async global::System.Threading.Tasks.Task EntrarComSenhaProvisoriaIndicaQueASenhaDeveSerTrocada()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Entrar com senha provisória indica que a senha deve ser trocada", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.GivenAsync("que existe um fornecedor \"maria@alfa.com.br\" com senha provisória para a empresa " +
                        "cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 19
    await testRunner.WhenAsync("eu entrar com o e-mail \"maria@alfa.com.br\" e a senha correta", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 20
    await testRunner.ThenAsync("eu recebo uma resposta 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 21
    await testRunner.AndAsync("o usuário do token deve precisar trocar a senha", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Mesma mensagem para senha incorreta e e-mail inexistente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SupplierUserSession - Login")]
        [global::Xunit.TraitAttribute("Description", "Mesma mensagem para senha incorreta e e-mail inexistente")]
        [global::Xunit.InlineDataAttribute("maria@alfa.com.br", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("ninguem@alfa.com.br", "3", new string[0])]
        public async global::System.Threading.Tasks.Task MesmaMensagemParaSenhaIncorretaEE_MailInexistente(string email, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mesma mensagem para senha incorreta e e-mail inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 24
    await testRunner.GivenAsync("que existe um fornecedor \"maria@alfa.com.br\" com senha definitiva para a empresa " +
                        "cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 25
    await testRunner.WhenAsync(string.Format("eu entrar com o e-mail \"{0}\" e a senha \"senha-errada\"", email), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 26
    await testRunner.ThenAsync("eu recebo uma resposta 401 Unauthorized", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 27
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"E-mail ou senha inválidos.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir a entrada de um fornecedor inativo")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SupplierUserSession - Login")]
        [global::Xunit.TraitAttribute("Description", "Não permitir a entrada de um fornecedor inativo")]
        public async global::System.Threading.Tasks.Task NaoPermitirAEntradaDeUmFornecedorInativo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir a entrada de um fornecedor inativo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.GivenAsync("que existe um fornecedor \"maria@alfa.com.br\" inativo para a empresa cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 36
    await testRunner.WhenAsync("eu entrar com o e-mail \"maria@alfa.com.br\" e a senha correta", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 37
    await testRunner.ThenAsync("eu recebo uma resposta 401 Unauthorized", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 38
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Usuário inativo. Procure o respons" +
                        "ável da Jotanunes.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Bloquear o acesso após tentativas inválidas seguidas")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SupplierUserSession - Login")]
        [global::Xunit.TraitAttribute("Description", "Bloquear o acesso após tentativas inválidas seguidas")]
        public async global::System.Threading.Tasks.Task BloquearOAcessoAposTentativasInvalidasSeguidas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bloquear o acesso após tentativas inválidas seguidas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 41
    await testRunner.GivenAsync("que existe um fornecedor \"maria@alfa.com.br\" com senha definitiva para a empresa " +
                        "cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 42
    await testRunner.AndAsync("que o fornecedor errou a senha 5 vezes seguidas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 43
    await testRunner.WhenAsync("eu entrar com o e-mail \"maria@alfa.com.br\" e a senha correta", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 44
    await testRunner.ThenAsync("eu recebo uma resposta 401 Unauthorized", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 45
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Acesso bloqueado temporariamente p" +
                        "or excesso de tentativas. Tente novamente em alguns minutos.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SupplierUserSession_LoginFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await SupplierUserSession_LoginFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
