// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Jotanunes.Internal.BddTests.Features.Api.SupplyRequestTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SupplyRequest_CruzamentoDeDocumentosDoPeriodoFeature : object, Xunit.IClassFixture<SupplyRequest_CruzamentoDeDocumentosDoPeriodoFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features/Api/SupplyRequestTests", "SupplyRequest - Cruzamento de documentos do período", "Como membro da equipe da Jotanunes\nQuero pedir e consultar o cruzamento dos docum" +
                "entos de cada período de uma solicitação\nPara ver inconsistências entre recibos," +
                " pagamentos, folhas de ponto e FGTS", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "CruzamentoSupplyRequest.feature"
#line hidden
        
        public SupplyRequest_CruzamentoDeDocumentosDoPeriodoFeature(SupplyRequest_CruzamentoDeDocumentosDoPeriodoFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
    await testRunner.GivenAsync("que existe uma empresa cadastrada com CNPJ \"11.222.333/0001-81\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 10
    await testRunner.AndAsync("que existe uma obra cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 11
    await testRunner.AndAsync("que existe uma solicitação de mão de obra aberta para a empresa e a obra cadastra" +
                    "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Api/SupplyRequestTests/CruzamentoSupplyRequest.feature.ndjson", 7);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Pedir o cruzamento de um período")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SupplyRequest - Cruzamento de documentos do período")]
        [global::Xunit.TraitAttribute("Description", "Pedir o cruzamento de um período")]
        public async global::System.Threading.Tasks.Task PedirOCruzamentoDeUmPeriodo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pedir o cruzamento de um período", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 14
    await testRunner.WhenAsync("eu pedir o cruzamento da solicitação cadastrada para o período de \"2026-07-01\" a " +
                        "\"2026-07-31\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 15
    await testRunner.ThenAsync("eu recebo uma resposta 202 Accepted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 16
    await testRunner.AndAsync("o relatório de cruzamento retornado está na fila para o período de \"2026-07-01\" a" +
                        " \"2026-07-31\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Listar os cruzamentos da solicitação")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SupplyRequest - Cruzamento de documentos do período")]
        [global::Xunit.TraitAttribute("Description", "Listar os cruzamentos da solicitação")]
        public async global::System.Threading.Tasks.Task ListarOsCruzamentosDaSolicitacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar os cruzamentos da solicitação", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("que foi pedido o cruzamento da solicitação cadastrada para o período de \"2026-07-" +
                        "01\" a \"2026-07-31\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 20
    await testRunner.WhenAsync("eu listar os cruzamentos da solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 21
    await testRunner.ThenAsync("eu recebo uma resposta 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 22
    await testRunner.AndAsync("a listagem de cruzamentos tem 1 relatório(s)", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Pedir o mesmo cruzamento duas vezes reaproveita o relatório")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SupplyRequest - Cruzamento de documentos do período")]
        [global::Xunit.TraitAttribute("Description", "Pedir o mesmo cruzamento duas vezes reaproveita o relatório")]
        public async global::System.Threading.Tasks.Task PedirOMesmoCruzamentoDuasVezesReaproveitaORelatorio()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pedir o mesmo cruzamento duas vezes reaproveita o relatório", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.GivenAsync("que foi pedido o cruzamento da solicitação cadastrada para o período de \"2026-07-" +
                        "01\" a \"2026-07-31\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 26
    await testRunner.AndAsync("que foi pedido o cruzamento da solicitação cadastrada para o período de \"2026-07-" +
                        "01\" a \"2026-07-31\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 27
    await testRunner.WhenAsync("eu listar os cruzamentos da solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 28
    await testRunner.ThenAsync("eu recebo uma resposta 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 29
    await testRunner.AndAsync("a listagem de cruzamentos tem 1 relatório(s)", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Listar os cruzamentos de uma solicitação inexistente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SupplyRequest - Cruzamento de documentos do período")]
        [global::Xunit.TraitAttribute("Description", "Listar os cruzamentos de uma solicitação inexistente")]
        public async global::System.Threading.Tasks.Task ListarOsCruzamentosDeUmaSolicitacaoInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar os cruzamentos de uma solicitação inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.WhenAsync("eu listar os cruzamentos de uma solicitação inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 33
    await testRunner.ThenAsync("eu recebo uma resposta 404 Not Found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 34
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Solicitação não encontrada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Pedir o cruzamento de uma solicitação inexistente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SupplyRequest - Cruzamento de documentos do período")]
        [global::Xunit.TraitAttribute("Description", "Pedir o cruzamento de uma solicitação inexistente")]
        public async global::System.Threading.Tasks.Task PedirOCruzamentoDeUmaSolicitacaoInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pedir o cruzamento de uma solicitação inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 37
    await testRunner.WhenAsync("eu pedir o cruzamento de uma solicitação inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 38
    await testRunner.ThenAsync("eu recebo uma resposta 404 Not Found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 39
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Solicitação não encontrada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SupplyRequest_CruzamentoDeDocumentosDoPeriodoFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await SupplyRequest_CruzamentoDeDocumentosDoPeriodoFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
