// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Jotanunes.External.BddTests.Features.Api.DocumentTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Document_EnvioFeature : object, Xunit.IClassFixture<Document_EnvioFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features/Api/DocumentTests", "Document - Envio", "Como fornecedor autenticado\nQuero enviar os documentos exigidos pela Jotanunes\nPa" +
                "ra manter a minha empresa em conformidade", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "EnvioDocument.feature"
#line hidden
        
        public Document_EnvioFeature(Document_EnvioFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
    await testRunner.GivenAsync("que existe uma empresa cadastrada com CNPJ \"11.222.333/0001-81\" que fornece mater" +
                    "ial e mão de obra", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 10
    await testRunner.AndAsync("que existe outra empresa cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 11
    await testRunner.AndAsync("que existe uma obra cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("que eu estou autenticado com senha definitiva", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Api/DocumentTests/EnvioDocument.feature.ndjson", 13);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Enviar um documento de habilitação")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Envio")]
        [global::Xunit.TraitAttribute("Description", "Enviar um documento de habilitação")]
        public async global::System.Threading.Tasks.Task EnviarUmDocumentoDeHabilitacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Enviar um documento de habilitação", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 15
    await testRunner.WhenAsync("eu enviar o Cartão de CNPJ em PDF", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 16
    await testRunner.ThenAsync("eu recebo uma resposta 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 17
    await testRunner.AndAsync("o documento enviado deve estar pendente de avaliação sem vínculo com solicitação", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Enviar um documento recorrente para uma solicitação aberta")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Envio")]
        [global::Xunit.TraitAttribute("Description", "Enviar um documento recorrente para uma solicitação aberta")]
        public async global::System.Threading.Tasks.Task EnviarUmDocumentoRecorrenteParaUmaSolicitacaoAberta()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Enviar um documento recorrente para uma solicitação aberta", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 20
    await testRunner.GivenAsync("que existe uma solicitação de mão de obra aberta para a empresa e a obra cadastra" +
                        "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 21
    await testRunner.WhenAsync("eu enviar a Folha de Pagamento para a solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 22
    await testRunner.ThenAsync("eu recebo uma resposta 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 23
    await testRunner.AndAsync("o documento enviado deve estar vinculado à solicitação cadastrada no período de r" +
                        "eferência atual", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 24
    await testRunner.AndAsync("a solicitação cadastrada deve estar em andamento", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Enviar um documento de trabalhador alocado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Envio")]
        [global::Xunit.TraitAttribute("Description", "Enviar um documento de trabalhador alocado")]
        public async global::System.Threading.Tasks.Task EnviarUmDocumentoDeTrabalhadorAlocado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Enviar um documento de trabalhador alocado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.GivenAsync("que existe uma solicitação de mão de obra aberta para a empresa e a obra cadastra" +
                        "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 28
    await testRunner.AndAsync("que existe um trabalhador \"José da Silva\" com CPF \"529.982.247-25\" cadastrado par" +
                        "a a empresa", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 29
    await testRunner.AndAsync("que o trabalhador cadastrado está alocado na solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 30
    await testRunner.WhenAsync("eu enviar a Folha de Ponto do trabalhador cadastrado para a solicitação cadastrad" +
                        "a", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 31
    await testRunner.ThenAsync("eu recebo uma resposta 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 32
    await testRunner.AndAsync("o documento enviado deve ser do trabalhador cadastrado com CPF \"52998224725\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir enviar documento recorrente de trabalhador que não está alocado na s" +
            "olicitação")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Envio")]
        [global::Xunit.TraitAttribute("Description", "Não permitir enviar documento recorrente de trabalhador que não está alocado na s" +
            "olicitação")]
        public async global::System.Threading.Tasks.Task NaoPermitirEnviarDocumentoRecorrenteDeTrabalhadorQueNaoEstaAlocadoNaSolicitacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir enviar documento recorrente de trabalhador que não está alocado na s" +
                    "olicitação", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.GivenAsync("que existe uma solicitação de mão de obra aberta para a empresa e a obra cadastra" +
                        "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 36
    await testRunner.AndAsync("que existe um trabalhador cadastrado para a empresa", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 37
    await testRunner.WhenAsync("eu enviar a Folha de Ponto do trabalhador cadastrado para a solicitação cadastrad" +
                        "a", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 38
    await testRunner.ThenAsync("eu recebo uma resposta 400 Bad Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 39
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Trabalhador não está alocado nesta" +
                        " solicitação.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir enviar documento de trabalhador sem informar o trabalhador")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Envio")]
        [global::Xunit.TraitAttribute("Description", "Não permitir enviar documento de trabalhador sem informar o trabalhador")]
        public async global::System.Threading.Tasks.Task NaoPermitirEnviarDocumentoDeTrabalhadorSemInformarOTrabalhador()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir enviar documento de trabalhador sem informar o trabalhador", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 41
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 42
    await testRunner.GivenAsync("que existe uma solicitação de mão de obra aberta para a empresa e a obra cadastra" +
                        "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 43
    await testRunner.WhenAsync("eu enviar a Folha de Ponto sem informar o trabalhador para a solicitação cadastra" +
                        "da", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 44
    await testRunner.ThenAsync("eu recebo uma resposta 400 Bad Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 45
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Trabalhador é obrigatório para est" +
                        "e tipo de documento.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir enviar documento que não se aplica ao fornecimento da solicitação")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Envio")]
        [global::Xunit.TraitAttribute("Description", "Não permitir enviar documento que não se aplica ao fornecimento da solicitação")]
        public async global::System.Threading.Tasks.Task NaoPermitirEnviarDocumentoQueNaoSeAplicaAoFornecimentoDaSolicitacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir enviar documento que não se aplica ao fornecimento da solicitação", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 48
    await testRunner.GivenAsync("que existe uma solicitação de material aberta para a empresa e a obra cadastradas" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 49
    await testRunner.WhenAsync("eu enviar a Folha de Pagamento para a solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 50
    await testRunner.ThenAsync("eu recebo uma resposta 400 Bad Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 51
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Este tipo de documento não se apli" +
                        "ca ao tipo de fornecimento da solicitação.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir enviar documento para uma solicitação encerrada")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Envio")]
        [global::Xunit.TraitAttribute("Description", "Não permitir enviar documento para uma solicitação encerrada")]
        public async global::System.Threading.Tasks.Task NaoPermitirEnviarDocumentoParaUmaSolicitacaoEncerrada()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir enviar documento para uma solicitação encerrada", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 54
    await testRunner.GivenAsync("que existe uma solicitação de mão de obra cancelada para a empresa e a obra cadas" +
                        "tradas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 55
    await testRunner.WhenAsync("eu enviar a Folha de Pagamento para a solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 56
    await testRunner.ThenAsync("eu recebo uma resposta 400 Bad Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 57
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Solicitação encerrada não aceita a" +
                        "lterações nem novos documentos.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir enviar documento para a solicitação de outra empresa")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Envio")]
        [global::Xunit.TraitAttribute("Description", "Não permitir enviar documento para a solicitação de outra empresa")]
        public async global::System.Threading.Tasks.Task NaoPermitirEnviarDocumentoParaASolicitacaoDeOutraEmpresa()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir enviar documento para a solicitação de outra empresa", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 59
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 60
    await testRunner.GivenAsync("que existe uma solicitação de material aberta para a outra empresa na obra cadast" +
                        "rada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 61
    await testRunner.WhenAsync("eu enviar a Folha de Pagamento para a solicitação da outra empresa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 62
    await testRunner.ThenAsync("eu recebo uma resposta 404 Not Found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 63
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Solicitação não encontrada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir enviar documento de um tipo inexistente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Envio")]
        [global::Xunit.TraitAttribute("Description", "Não permitir enviar documento de um tipo inexistente")]
        public async global::System.Threading.Tasks.Task NaoPermitirEnviarDocumentoDeUmTipoInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir enviar documento de um tipo inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 65
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 66
    await testRunner.WhenAsync("eu enviar um documento de um tipo inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 67
    await testRunner.ThenAsync("eu recebo uma resposta 404 Not Found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 68
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Tipo de documento não encontrado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Não permitir enviar arquivo inválido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Envio")]
        [global::Xunit.TraitAttribute("Description", "Não permitir enviar arquivo inválido")]
        [global::Xunit.InlineDataAttribute("um arquivo de texto", "Formato de arquivo não aceito. Envie PDF, PNG ou JPEG.", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("um arquivo vazio", "O arquivo enviado está vazio.", "10", new string[0])]
        public async global::System.Threading.Tasks.Task NaoPermitirEnviarArquivoInvalido(string arquivo, string mensagem, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("arquivo", arquivo);
            argumentsOfScenario.Add("mensagem", mensagem);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir enviar arquivo inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 71
    await testRunner.WhenAsync(string.Format("eu enviar o Cartão de CNPJ com {0}", arquivo), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 72
    await testRunner.ThenAsync("eu recebo uma resposta 400 Bad Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 73
    await testRunner.AndAsync(string.Format("eu recebo uma resposta de erro com a mensagem \"{0}\"", mensagem), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Document_EnvioFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await Document_EnvioFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
