// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Jotanunes.External.BddTests.Features.Api.WorkerTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Worker_AlocacaoFeature : object, Xunit.IClassFixture<Worker_AlocacaoFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features/Api/WorkerTests", "Worker - Alocação", "Como fornecedor autenticado\nQuero informar quais trabalhadores estão alocados em " +
                "cada obra\nPara que a Jotanunes saiba quem está na obra e cobre os documentos de " +
                "cada um", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AlocacaoWorker.feature"
#line hidden
        
        public Worker_AlocacaoFeature(Worker_AlocacaoFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
    await testRunner.GivenAsync("que existe uma empresa cadastrada com CNPJ \"11.222.333/0001-81\" que fornece mater" +
                    "ial e mão de obra", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 10
    await testRunner.AndAsync("que existe outra empresa cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 11
    await testRunner.AndAsync("que existe uma obra cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("que eu estou autenticado com senha definitiva", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Api/WorkerTests/AlocacaoWorker.feature.ndjson", 8);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Alocar um trabalhador numa solicitação de mão de obra")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker - Alocação")]
        [global::Xunit.TraitAttribute("Description", "Alocar um trabalhador numa solicitação de mão de obra")]
        public async global::System.Threading.Tasks.Task AlocarUmTrabalhadorNumaSolicitacaoDeMaoDeObra()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Alocar um trabalhador numa solicitação de mão de obra", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 15
    await testRunner.GivenAsync("que existe uma solicitação de mão de obra aberta para a empresa e a obra cadastra" +
                        "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.AndAsync("que existe um trabalhador cadastrado para a empresa", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 17
    await testRunner.WhenAsync("eu alocar o trabalhador cadastrado na solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 18
    await testRunner.ThenAsync("eu recebo uma resposta 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 19
    await testRunner.AndAsync("a solicitação cadastrada deve ter apenas o trabalhador cadastrado alocado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir alocar o mesmo trabalhador duas vezes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker - Alocação")]
        [global::Xunit.TraitAttribute("Description", "Não permitir alocar o mesmo trabalhador duas vezes")]
        public async global::System.Threading.Tasks.Task NaoPermitirAlocarOMesmoTrabalhadorDuasVezes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir alocar o mesmo trabalhador duas vezes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 22
    await testRunner.GivenAsync("que existe uma solicitação de mão de obra aberta para a empresa e a obra cadastra" +
                        "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 23
    await testRunner.AndAsync("que existe um trabalhador cadastrado para a empresa", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 24
    await testRunner.AndAsync("que o trabalhador cadastrado está alocado na solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 25
    await testRunner.WhenAsync("eu alocar o trabalhador cadastrado na solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 26
    await testRunner.ThenAsync("eu recebo uma resposta 400 Bad Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 27
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Trabalhador já está alocado nesta " +
                        "solicitação.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir alocar além da quantidade de trabalhadores necessária")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker - Alocação")]
        [global::Xunit.TraitAttribute("Description", "Não permitir alocar além da quantidade de trabalhadores necessária")]
        public async global::System.Threading.Tasks.Task NaoPermitirAlocarAlemDaQuantidadeDeTrabalhadoresNecessaria()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir alocar além da quantidade de trabalhadores necessária", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync("que existe uma solicitação de mão de obra aberta para a empresa e a obra cadastra" +
                        "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 31
    await testRunner.AndAsync("que a solicitação cadastrada já tem todos os trabalhadores necessários alocados", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 32
    await testRunner.AndAsync("que existe um trabalhador cadastrado para a empresa", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 33
    await testRunner.WhenAsync("eu alocar o trabalhador cadastrado na solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 34
    await testRunner.ThenAsync("eu recebo uma resposta 400 Bad Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 35
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"A solicitação já tem os 3 trabalha" +
                        "dores necessários alocados. Desaloque um antes de alocar outro.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir alocar trabalhador em solicitação de material")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker - Alocação")]
        [global::Xunit.TraitAttribute("Description", "Não permitir alocar trabalhador em solicitação de material")]
        public async global::System.Threading.Tasks.Task NaoPermitirAlocarTrabalhadorEmSolicitacaoDeMaterial()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir alocar trabalhador em solicitação de material", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 38
    await testRunner.GivenAsync("que existe uma solicitação de material aberta para a empresa e a obra cadastradas" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 39
    await testRunner.AndAsync("que existe um trabalhador cadastrado para a empresa", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 40
    await testRunner.WhenAsync("eu alocar o trabalhador cadastrado na solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 41
    await testRunner.ThenAsync("eu recebo uma resposta 400 Bad Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 42
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Só é possível alocar trabalhadores" +
                        " em solicitações de mão de obra.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir alocar trabalhador de outra empresa")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker - Alocação")]
        [global::Xunit.TraitAttribute("Description", "Não permitir alocar trabalhador de outra empresa")]
        public async global::System.Threading.Tasks.Task NaoPermitirAlocarTrabalhadorDeOutraEmpresa()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir alocar trabalhador de outra empresa", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 45
    await testRunner.GivenAsync("que existe uma solicitação de mão de obra aberta para a empresa e a obra cadastra" +
                        "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 46
    await testRunner.AndAsync("que existe um trabalhador cadastrado para a outra empresa", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 47
    await testRunner.WhenAsync("eu alocar o trabalhador da outra empresa na solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 48
    await testRunner.ThenAsync("eu recebo uma resposta 404 Not Found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 49
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Trabalhador não encontrado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Desalocar um trabalhador mantém o histórico")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Worker - Alocação")]
        [global::Xunit.TraitAttribute("Description", "Desalocar um trabalhador mantém o histórico")]
        public async global::System.Threading.Tasks.Task DesalocarUmTrabalhadorMantemOHistorico()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Desalocar um trabalhador mantém o histórico", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 52
    await testRunner.GivenAsync("que existe uma solicitação de mão de obra aberta para a empresa e a obra cadastra" +
                        "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 53
    await testRunner.AndAsync("que existe um trabalhador cadastrado para a empresa", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 54
    await testRunner.AndAsync("que o trabalhador cadastrado está alocado na solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 55
    await testRunner.WhenAsync("eu desalocar o trabalhador cadastrado da solicitação cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 56
    await testRunner.ThenAsync("eu recebo uma resposta 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 57
    await testRunner.AndAsync("a solicitação cadastrada não deve ter trabalhadores alocados", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 58
    await testRunner.AndAsync("o histórico da solicitação cadastrada deve mostrar o trabalhador cadastrado desal" +
                        "ocado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Worker_AlocacaoFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await Worker_AlocacaoFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
