// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Jotanunes.Internal.BddTests.Features.Api.DocumentTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Document_AnaliseAutomaticaFeature : object, Xunit.IClassFixture<Document_AnaliseAutomaticaFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features/Api/DocumentTests", "Document - Análise automática", "Como membro da equipe da Jotanunes\nQuero consultar o parecer automático de um doc" +
                "umento e pedir uma nova análise\nPara avaliar os documentos com apoio da leitura " +
                "automática", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AnaliseDocument.feature"
#line hidden
        
        public Document_AnaliseAutomaticaFeature(Document_AnaliseAutomaticaFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
    await testRunner.GivenAsync("que existe uma empresa cadastrada com CNPJ \"11.222.333/0001-81\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Api/DocumentTests/AnaliseDocument.feature.ndjson", 8);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Consultar a análise de um documento")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Análise automática")]
        [global::Xunit.TraitAttribute("Description", "Consultar a análise de um documento")]
        public async global::System.Threading.Tasks.Task ConsultarAAnaliseDeUmDocumento()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar a análise de um documento", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.GivenAsync("que existe um documento de habilitação pendente enviado pela empresa cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 13
    await testRunner.AndAsync("que o documento cadastrado tem uma análise pendente", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 14
    await testRunner.WhenAsync("eu consultar a análise do documento cadastrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 15
    await testRunner.ThenAsync("eu recebo uma resposta 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 16
    await testRunner.AndAsync("a análise retornada deve estar com status \"Pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Consultar a análise de um documento que ainda não foi analisado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Análise automática")]
        [global::Xunit.TraitAttribute("Description", "Consultar a análise de um documento que ainda não foi analisado")]
        public async global::System.Threading.Tasks.Task ConsultarAAnaliseDeUmDocumentoQueAindaNaoFoiAnalisado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar a análise de um documento que ainda não foi analisado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("que existe um documento de habilitação pendente enviado pela empresa cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 20
    await testRunner.WhenAsync("eu consultar a análise do documento cadastrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 21
    await testRunner.ThenAsync("eu recebo uma resposta 404 Not Found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 22
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Análise do documento não encontrad" +
                        "a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Pedir nova análise de um documento já analisado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Análise automática")]
        [global::Xunit.TraitAttribute("Description", "Pedir nova análise de um documento já analisado")]
        public async global::System.Threading.Tasks.Task PedirNovaAnaliseDeUmDocumentoJaAnalisado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pedir nova análise de um documento já analisado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.GivenAsync("que existe um documento de habilitação pendente enviado pela empresa cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 26
    await testRunner.AndAsync("que o documento cadastrado tem uma análise concluída", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 27
    await testRunner.WhenAsync("eu pedir uma nova análise do documento cadastrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 28
    await testRunner.ThenAsync("eu recebo uma resposta 202 Accepted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 29
    await testRunner.AndAsync("a análise retornada deve estar com status \"Pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Pedir análise de um documento enviado antes da análise automática existir")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Análise automática")]
        [global::Xunit.TraitAttribute("Description", "Pedir análise de um documento enviado antes da análise automática existir")]
        public async global::System.Threading.Tasks.Task PedirAnaliseDeUmDocumentoEnviadoAntesDaAnaliseAutomaticaExistir()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pedir análise de um documento enviado antes da análise automática existir", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.GivenAsync("que existe um documento de habilitação pendente enviado pela empresa cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 33
    await testRunner.WhenAsync("eu pedir uma nova análise do documento cadastrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 34
    await testRunner.ThenAsync("eu recebo uma resposta 202 Accepted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 35
    await testRunner.AndAsync("a análise retornada deve estar com status \"Pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Não permitir pedir nova análise enquanto a anterior está na fila")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Análise automática")]
        [global::Xunit.TraitAttribute("Description", "Não permitir pedir nova análise enquanto a anterior está na fila")]
        public async global::System.Threading.Tasks.Task NaoPermitirPedirNovaAnaliseEnquantoAAnteriorEstaNaFila()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Não permitir pedir nova análise enquanto a anterior está na fila", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 38
    await testRunner.GivenAsync("que existe um documento de habilitação pendente enviado pela empresa cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 39
    await testRunner.AndAsync("que o documento cadastrado tem uma análise pendente", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 40
    await testRunner.WhenAsync("eu pedir uma nova análise do documento cadastrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 41
    await testRunner.ThenAsync("eu recebo uma resposta 400 Bad Request", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 42
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"A análise deste documento já está " +
                        "na fila.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Pedir análise de um documento inexistente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Document - Análise automática")]
        [global::Xunit.TraitAttribute("Description", "Pedir análise de um documento inexistente")]
        public async global::System.Threading.Tasks.Task PedirAnaliseDeUmDocumentoInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pedir análise de um documento inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 45
    await testRunner.WhenAsync("eu pedir uma nova análise de um documento inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 46
    await testRunner.ThenAsync("eu recebo uma resposta 404 Not Found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 47
    await testRunner.AndAsync("eu recebo uma resposta de erro com a mensagem \"Documento não encontrado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Document_AnaliseAutomaticaFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await Document_AnaliseAutomaticaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
