// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Jotanunes.External.BddTests.Features.Api.AuthTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AuthCheck_SupplyRequestFeature : object, Xunit.IClassFixture<AuthCheck_SupplyRequestFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features/Api/AuthTests", "Auth Check - SupplyRequest", "Como um usuário do sistema\nQuero ter a segurança de que o acesso às solicitações " +
                "de fornecimento está sendo corretamente verificado\nPara garantir que apenas forn" +
                "ecedores autenticados, com senha definitiva e da própria empresa possam consultá" +
                "-las", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AuthCheckSupplyRequest.feature"
#line hidden
        
        public AuthCheck_SupplyRequestFeature(AuthCheck_SupplyRequestFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
    await testRunner.GivenAsync("que existe uma empresa cadastrada com CNPJ \"11.222.333/0001-81\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 10
    await testRunner.AndAsync("que existe uma obra cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 11
    await testRunner.AndAsync("que existe uma solicitação de material aberta para a empresa e a obra cadastradas" +
                    "", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Api/AuthTests/AuthCheckSupplyRequest.feature.ndjson", 8);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Verificar acesso aos endpoints de solicitação de fornecimento")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Auth Check - SupplyRequest")]
        [global::Xunit.TraitAttribute("Description", "Verificar acesso aos endpoints de solicitação de fornecimento")]
        [global::Xunit.InlineDataAttribute("eu listar as solicitações da minha empresa", "não estou autenticado", "401 Unauthorized", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("eu listar as solicitações da minha empresa", "estou autenticado com senha provisória", "403 Forbidden", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("eu consultar a solicitação cadastrada", "não estou autenticado", "401 Unauthorized", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("eu consultar a solicitação cadastrada", "estou autenticado com senha provisória", "403 Forbidden", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("eu consultar a solicitação cadastrada", "estou autenticado como fornecedor de outra empresa", "404 Not Found", "4", new string[0])]
        public async global::System.Threading.Tasks.Task VerificarAcessoAosEndpointsDeSolicitacaoDeFornecimento(string executarAcao, string descricaoAutenticacao, string respostaEsperada, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("executarAcao", executarAcao);
            argumentsOfScenario.Add("descricaoAutenticacao", descricaoAutenticacao);
            argumentsOfScenario.Add("respostaEsperada", respostaEsperada);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verificar acesso aos endpoints de solicitação de fornecimento", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 14
    await testRunner.GivenAsync(string.Format("que eu {0}", descricaoAutenticacao), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 15
    await testRunner.WhenAsync(string.Format("{0}", executarAcao), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 16
    await testRunner.ThenAsync(string.Format("eu recebo uma resposta {0}", respostaEsperada), ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Fornecedor com senha provisória é orientado a trocar a senha")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Auth Check - SupplyRequest")]
        [global::Xunit.TraitAttribute("Description", "Fornecedor com senha provisória é orientado a trocar a senha")]
        public async global::System.Threading.Tasks.Task FornecedorComSenhaProvisoriaEOrientadoATrocarASenha()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fornecedor com senha provisória é orientado a trocar a senha", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.GivenAsync("que eu estou autenticado com senha provisória", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 28
    await testRunner.WhenAsync("eu listar as solicitações da minha empresa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 29
    await testRunner.ThenAsync("eu recebo uma resposta 403 Forbidden", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 30
    await testRunner.AndAsync("a resposta indica que é preciso trocar a senha provisória", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AuthCheck_SupplyRequestFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await AuthCheck_SupplyRequestFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
